# Generated by Django 4.2.2 on 2023-06-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_task_description_remove_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('OP', 'OPEN'), ('WO', 'WORKING'), ('DO', 'DONE'), ('OV', 'OVERDUE')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='Tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
