# Generated by Django 4.2.2 on 2023-06-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_description_task_due_date_task_status_task_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
